name: Travelog CI

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle
                  
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        
      - name: Access google place key
        env:
          google_map_key: ${{ secrets.GOOGLE_MAP_KEY }}
        run: echo google_map_key=\"$google_map_key\" >> ./local.properties
        
      - name: Access tour api key
        env:
          tour_api_key: ${{ secrets.TOUR_API_KEY }}
        run: echo tour_api_key=\"$tour_api_key\" >> ./local.properties
                
      - name: Access new tour api key
        env:
          new_tour_api_key: ${{ secrets.NEW_TOUR_API_KEY }}
        run: echo new_tour_api_key=\"$new_tour_api_key\" >> ./local.properties
        
      - name: Access google map key
        env:
          google_map_key: ${{ secrets.GOOGLE_MAP_KEY }}
        run: echo newGoogleMapKey=google_map_key >> ./local.properties
        
      - name: Unit tests
        run: ./gradlew test --stacktrace
 
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Access google place key
      env:
          google_map_key: ${{ secrets.GOOGLE_MAP_KEY }}
      run: echo google_map_key=\"$google_map_key\" >> ./local.properties
       
    - name: Access tour api key
      env:
          tour_api_key: ${{ secrets.TOUR_API_KEY }}
      run: echo tour_api_key=\"$tour_api_key\" >> ./local.properties
                
    - name: Access new tour api key
      env:
        new_tour_api_key: ${{ secrets.NEW_TOUR_API_KEY }}
      run: echo new_tour_api_key=\"$new_tour_api_key\" >> ./local.properties
      
    - name: Access google map key
      env:
        google_map_key: ${{ secrets.GOOGLE_MAP_KEY }}
        run: echo newGoogleMapKey=google_map_key >> ./local.properties
      
    - name: Build with Gradle
      run: ./gradlew build
